echo on

setlocal ENABLEDELAYEDEXPANSION

set target_platform=%1
set target_configuration=%2
if "%target_platform%"=="" set target_platform=x64

if /I "%target_platform%" equ "all" (
  if "%target_configuration%"=="" (
    set target_configuration=all
  )
  call %0 x86 !target_configuration!
  call %0 x64 !target_configuration!
  call %0 arm64 !target_configuration!
  goto :eof
)

if /I "%target_configuration%" equ "all" (
  call %0 %target_platform% Debug
  call %0 %target_platform% Release
  goto :eof
)

if "%target_configuration%"=="" (
 set target_configuration=Debug
)

REM Find base.h in _reference/ and build/ and use that as the projection root
for /F "delims=" %%a in ('dir /s /b %~p0\_reference\base.h') do set reference_projection_root=%%~dpa
for /F "delims=" %%a in ('dir /s /b %~p0\build\base.h') do set build_projection_root=%%~dpa

if "%reference_projection_root%" == "" (
 echo Reference projection output not found under %~p0\_reference - run build_prior_projection.cmd to generate reference projections
 goto :EOF
)
if "%build_projection_root%" == "" (
 echo Build projection output not found under %~p0\build - run build_projection.cmd to generate build projections
 goto :EOF
)

echo Removing version stamps from %reference_projection_root%
powershell -Command "gci -r -path %reference_projection_root% -include *.h,*.ixx | %%{ (get-content $_) -replace 'was generated by.*|CPPWINRT_VERSION.*','' | set-content $_ }"

echo Removing version stamps from %build_projection_root%
powershell -Command "gci -r -path %build_projection_root% -include *.h,*.ixx | %%{ (get-content $_) -replace 'was generated by.*|CPPWINRT_VERSION.*','' | set-content $_ }"
